### ISSUE TITLE
Add support for `task.outputs.paramters`

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/queenbee-luigi#9]
@AntoineDao, for a sample file like the one that you shared where do you expect to see the output parameters? Will it be a file? Or should I just print out the parameters to stdout? When would you think we will use parameters instead of artifacts in one of our typical recipes?

```yaml
metadata:
  name: simple-recipe
  version: 0.1.0

dependencies:
- type: operator
  name: whalesay
  version: 0.1.0
  source: https://pollination.github.io/shed

digest: 631aaac41d883a47ec5563b32424e65fa5e6279aeb6bfa620b9b8dc468f14b52

templates:
- name: 66e33175da38c55cc4d4675e5d58ee69cd8eb09ca161cfe6eb95e5ac96304d58/say-hi
  description: Make the whale say something!
  inputs:
    parameters:
    - name: message
      default: hi
      description: What the whale will say
      required: false
    artifacts: []
  command: cowsay {{inputs.parameters.message}} | tee /tmp/hello_world.txt
  outputs:
    parameters:
    - name: whale-said
      path: /tmp/hello_world.txt
    artifacts:
    - name: whale-said-file
      path: /tmp/hello_world.txt
  config:
    docker:
      image: docker/whalesay:latest
      workdir: /cowsay

flow:
- name: 631aaac41d883a47ec5563b32424e65fa5e6279aeb6bfa620b9b8dc468f14b52/main
  inputs:
    parameters:
    - name: thing-to-say
      default: hi
      description: What the whale will say
    artifacts: []
  fail_fast: true
  tasks:
  - name: say-something
    template: 66e33175da38c55cc4d4675e5d58ee69cd8eb09ca161cfe6eb95e5ac96304d58/say-hi
    arguments:
      parameters:
      - name: message
        from:
          type: inputs
          variable: thing-to-say
      artifacts: []
    outputs:
      parameters:
      - name: whale-said
      artifacts: []
  outputs:
    parameters:
    - name: what-the-whale-said
      from:
        type: tasks
        name: say-something
        variable: whale-said
    artifacts: []
```
